import client from "@/libs/apollo-client";
import { gql } from "@apollo/client";
import Head from "next/head";

export default function Home({ countries }) {
  const flag = String.fromCodePoint(0x1f1e6, 0x1f1e9);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container max-w-sm mx-auto py-10">
        <header className="py-11 bg-gradient-to-br  from-indigo-400 to-sky-400 rounded-lg  p-2">
          <h1 className="text-4xl font-bold tracking-wide text-indigo-50 text-center drop-shadow">
            GraphQL Country
          </h1>
        </header>
        <hr className="my-10 p-[1px] rounded-full bg-gradient-to-r from-indigo-400 via-purple-400 to-sky-400" />
        <section>
          <ul className="">
            {countries.map((country, key) => (
              <li
                key={key}
                className="py-2 px-3 rounded-md bg-slate-100 mb-2 border border-slate-400 border-dashed"
              >
                <p className="font-semibold text-slate-800">
                  {key + 1}. {country.name}
                </p>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </>
  );
}

//* SERVER SIDE PROPS
export async function getServerSideProps() {
  const query = gql`
    query Countries {
      countries {
        code
        name
        emoji
      }
    }
  `;
  const { data } = await client.query({ query });

  return {
    props: {
      countries: data.countries,
    },
  };
}
